# Generated by Django 3.0.3 on 2020-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('styleno', models.IntegerField()),
                ('orderqty', models.IntegerField()),
                ('ordercd', models.DateField()),
                ('plancd', models.DateField()),
                ('ocd', models.DateField()),
                ('ltf', models.IntegerField()),
                ('ltb', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='exp',
        ),
    ]
