# Generated by Django 3.0.3 on 2020-02-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadplan', '0002_auto_20200210_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderdetails',
            new_name='Ord',
        ),
    ]
