# Generated by Django 3.0.3 on 2020-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadplan', '0003_auto_20200210_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineno', models.IntegerField()),
                ('noo', models.FloatField()),
                ('workdays', models.FloatField()),
                ('dwh', models.FloatField()),
                ('absent', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('mac', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('ltlc', models.IntegerField()),
                ('orderqty', models.IntegerField()),
                ('smv', models.IntegerField()),
                ('crm', models.FloatField()),
                ('capd', models.FloatField()),
                ('crd', models.FloatField()),
            ],
        ),
    ]
